### ISSUE TITLE
Change default branch's name

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#102]
As Mandrel is not using the default branch (currently called `master`) as the development branch and #98 essentially makes the default branch just a landing page. It seems like we could rename the default branch in an effort to be more inclusive [1].

Please use this issue to raise any concerns and/or to suggest a name for the default branch.
Some names I have thought about:

* `welcome`
* `readme`
* `default`
* `main`

[1] https://sfconservancy.org/news/2020/jun/23/gitbranchname/

**Comment by adinn** [comment]
I agree this is a good idea. I'm happy with any of the above suggestions. If you want an actual pick then I'll go for default.

**Comment by zakkak** [comment]
For the record I am also adding a reference to @maxandersen 's comment https://github.com/graalvm/mandrel/pull/98#issuecomment-671294366 and my reply https://github.com/graalvm/mandrel/pull/98#issuecomment-671300080

**Comment by zakkak** [comment]
One way to make the transition in a safe manner without any inconvenience is to create the new branch and make it the default, while keeping in in sync with `master` (which will no longer be the default though) through https://github.com/graalvm/mandrel/blob/master/.github/workflows/repo-sync.yml

What do you think about this approach @maxandersen ?

**Comment by zakkak** [comment]
Since I see no objections I am going to proceed with the change as mentioned above ^^

**Comment by maxandersen** [comment]
Sorry thought I already responded that it sounds good:)
