### ISSUE TITLE
mandrel-20.1.0.1.Final release text says Alpha2 not Final

### ISSUE THREAD

**Issue by rsvoboda** [graalvm/mandrel#105]
https://github.com/graalvm/mandrel/releases/tag/mandrel-20.1.0.1.Final

Mandrel 20.1.0.1.Alpha2 is a downstream distribution of the GraalVM community edition 20.1.
 =>
Mandrel 20.1.0.1.Final is a downstream distribution of the GraalVM community edition 20.1.

@Karm fyi

**Comment by Karm** [comment]
@rsvoboda This is fixed now. Thx.
