### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#114]
MacOS builds should be relatively easy to produce and test, however, there are still some roadblocks in our way.

To my knowledge these are:
- [x] There is no available vanilla build of OpenJDK for MacOS that includes static-libs 
- [x] `mandrel-packaging` is known to have some issues on MacOS (See https://github.com/graalvm/mandrel-packaging/issues/42)
- [x] We lack HW for testing and releasing on MacOS (see https://github.com/graalvm/mandrel/issues/114#issuecomment-1016273406)

Please comment bellow if you are aware of any additional issues.

**Comment by jerboaa** [comment]
FYI:

Via Eclipse Temurin there are (untested) Mac OS X static-libs now.

JDK 17: https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.1%2B12

**Comment by debu999** [comment]
Anything on this getting traction. Definitely a good thing to move forward with this.

**Comment by zakkak** [comment]
> Anything on this getting traction. 

No, not yet. At the moment it looks like we would need to rely on GH actions to provide MacOS releases while Linux and Windows releases are built and tested internally. @Karm WDYT?

**Comment by Karm** [comment]
Relying on doing Mac releases on GH actions is not an option, so there are no MacOS releases planned at the time of writing. 

When (rather than if) that changes, we will update this issue :+1:

**Comment by raupachz** [comment]
Any updates?

**Comment by jerboaa** [comment]
I don't think our stance has changed on this one, sorry.

**Comment by zakkak** [comment]
https://github.com/graalvm/mandrel-packaging/pull/339 enables building Mandrel for MacOS x86. Next step is figuring out if it works on M1 as well. Last, we will need some infrastructure as mentioned in https://github.com/graalvm/mandrel/issues/114#issuecomment-1016273406.

**Comment by Karm** [comment]
@zakkak Thx for the addition to the mandrel-packaging. 

~Releasing without test infrastructure in place is a no go. I would like to avoid any misunderstanding on the front of potentially available released bits.~

My note is redundant. I am sorry. I managed to miss the end of your previous comment :+1:

**Comment by Karm** [comment]
Mandrel team has the M2 Pro systems now, so we will revisit this issue presently.

**Comment by Karm** [comment]
We have preview builds, now in testing...
```
[INFO]  Java version: 21.0.3+9-LTS, vendor version: Mandrel-23.1.3.2-dev49b42155870
[INFO]  Graal compiler: optimization level: 2, target machine: armv8-a
[INFO]  C compiler: cc (apple, arm64, 15.0.0)
```

**Comment by Karm** [comment]
@debu999  @raupachz 
Done: https://groups.google.com/u/1/g/quarkus-dev/c/LC11CnPHqTw

**Comment by raupach-e2n** [comment]
Well done! Congratulations 🥳
