### ISSUE TITLE
Native image, executable debugging, GDB: `sources` not properly generated while building from a jar

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#139]
Hello,

Although it seems gdb is aware of the source files, e.g. it is able to set breakpoints, it doesn't seem to list the actual source code when prompted. It struck me while developing automation for gdb session as my test apps are packaged as jars by Maven.
When I compile the app in the default package and use the class directly, the behavior seems correct.

# Works :heavy_check_mark: 
See: [works.zip](https://github.com/graalvm/mandrel/files/5247195/works.zip)

```bash
export JAVA_HOME=~/workspaceRH/mandrel-release/mandrel-java11-20.1.0.2.Final/;export PATH=${JAVA_HOME}/bin:${PATH}
javac Main.java 
native-image -H:GenerateDebugInfo=1 -H:+PreserveFramePointer -H:-DeleteLocalSymbols Main
gdb ./main
Reading symbols from ./main...done.
(gdb) b Main.java:76
Breakpoint 1 at 0x405677: file Main.java, line 76.
(gdb) b Main.java:70
Breakpoint 2 at 0x4057cb: file Main.java, line 70.
(gdb) run < test_data_small.txt
Starting program: /tmp/GUGU/main < test_data_small.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Q to quit

Breakpoint 1, Main::main(java.lang.String[])()void () at Main.java:76
76                  if ("Q".equals(l)) {
(gdb) list
71                      ays.add(new ClassA(myNumber, myString));
72                      myString = null;
73                      myNumber = Integer.MIN_VALUE;
74                  }
75                  String l = sc.nextLine();
76                  if ("Q".equals(l)) {
77                      thisIsTheEnd(ays);
78                  }
79                  if (myNumber == Integer.MIN_VALUE) {
80                      Matcher m = p.matcher(l);
```

# Does not work :x: 
See: [does-not-work.zip](https://github.com/graalvm/mandrel/files/5247194/does-not-work.zip)
Maven used: Apache Maven 3.6.3

```bash
mvn package
native-image -H:GenerateDebugInfo=1 -H:+PreserveFramePointer -H:-DeleteLocalSymbols -jar target/debug-symbols-smoke.jar target/debug-symbols-smoke
gdb ./target/debug-symbols-smoke 
Reading symbols from ./target/debug-symbols-smoke...done.
(gdb) b Main.java:76
Breakpoint 1 at 0x4cdb0c: file debug_symbols_smoke/Main.java, line 76.
(gdb) b Main.java:70
Breakpoint 2 at 0x4cdaf9: file debug_symbols_smoke/Main.java, line 70.
(gdb) run < test_data_small.txt
Starting program: /tmp/does-not-work/target/debug-symbols-smoke < test_data_small.txt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Q to quit

Breakpoint 2, debug_symbols_smoke.Main::main(java.lang.String[])()void () at debug_symbols_smoke/Main.java:70
70  debug_symbols_smoke/Main.java: No such file or directory.
(gdb) list
65  in debug_symbols_smoke/Main.java
```

FYI: @adinn 

I realize the trouble might be in the generated `sources` dir and my usage of the jar to build the image, but it would be at least a case for a doc update...

Thx for hints

System: Linux amd64
GDB: 7.12
Mandrel: 20.1.0.2.Final

**Comment by zakkak** [comment]
@Karm does `mvn package` generate an archive with the sources along with `target/debug-symbols-smoke.jar`? If not, that's the issue here.

When using jars Graal is looking for `target/debug-symbols-smoke-sources.jar` or `target/debug-symbols-smoke.zip` to get the source files from.
See https://github.com/graalvm/mandrel/blob/mandrel/20.1/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceCache.java#L198-L217

**Comment by Karm** [comment]
@zakkak I have amended the description, it is indeed just `sources` generation.       I will make maven generate the sources jar and see...

**Comment by Karm** [comment]
@zakkak 

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

Fixed it :-)     Thx for [:duck: ](https://en.wikipedia.org/wiki/Rubber_duck_debugging)
