### ISSUE TITLE
Publish SHA256 of distributions

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#168]
It would be nice to start publishing SHA256 files for our distributions like GraalVM CE started doing in 20.3 https://github.com/graalvm/graalvm-ce-builds/releases

**Comment by Karm** [comment]
@zakkak i.e. to replace SHA1 we have been using since day one with SHA256 or do you mean to hash something else?

**Comment by zakkak** [comment]
Either replace or add, just to make SHA256 available for consistency with GraalVM CE.

**Comment by zakkak** [comment]
[mandrel-packaging](https://github.com/graalvm/mandrel-packaging/pull/80) now takes care of this. 
Release 20.3.0.0.Beta2 is the first to feature SHA256 hashes along with the SHA1 ones.
