### ISSUE TITLE
Linker fails: liblcms.a(LCMS.o): In function `JNI_OnLoad_dynamic_lcms': undefined reference to `cmsSetLogErrorHandler'

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#190]
## Description

Builder image 20.3-1 doesn't let Quarkus 1.7.6.Final TS pass, There are numerous failures to build integration tests cases, e.g. google-cloud-functions-http, grpc-proto-v2, grpc-interceptors, webjars-locator and more. All those failures have a linker failure in common:

```
 /usr/lib/jvm/java-11-openjdk-11.0.9.11-3.el8_3.x86_64/lib/static/linux-amd64/glibc/liblcms.a(LCMS.o): In function `JNI_OnLoad_dynamic_lcms':
/builddir/build/BUILD/java-11-openjdk-11.0.9.11-3.el8_3.x86_64/openjdk/src/java.desktop/share/native/liblcms/LCMS.c:140: undefined reference to `cmsSetLogErrorHandler'
collect2: error: ld returned 1 exit status
```

Example of a full log: [google-cloud-functions-http](https://gist.github.com/Karm/d4f4dbd5c631681ff61387ee1a18a688), [grpc-proto-v2](https://gist.github.com/Karm/cbd600ceee2b200a3356bd2871632a0c)

Builder image: registry-proxy.engineering.redhat.com/rh-osbs/quarkus-quarkus-mandrel-20-rhel8:20.3-1
Mandrel: GraalVM Version 20.3.0.0_0-6 (Mandrel Distribution) (Java Version 11.0.9.1+1-LTS)
Host: RHEL 8
Java used to start the TS: [openjdk-11.0.9.1_1](https://github.com/AdoptOpenJDK/openjdk11-upstream-binaries/releases/tag/jdk-11.0.9.1%2B1)

I will poke around it tomorrow and re-run on a neighbor executor...

**Comment by Karm** [comment]
Might interest: @jerboaa

**Comment by zakkak** [comment]
@Karm Quarkus 1.7.6 is not compatible with Graal/Mandrel 20.3, you need to use 20.1
