### ISSUE TITLE
Extra linker flags needed when building apps that depend on AWT and Mandrel is based on an OpenJDK build that depends on system libraries

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#208]
## Description

OpenJDK builds that ship with Fedora and Ubuntu (and possibly other distributions) depend on system libraries, while the [OpenJDK Project Builds distributed through AdoptOpenJDK](https://adoptopenjdk.net/upstream.html?variant=openjdk11&ga=ga) use OpenJDK in-tree libraries instead.

On Fedora 33 running: 
```shell
for i in $(rpm -ql java-11-openjdk-headless | grep \\.so)
    do
    output=$(ldd $i | grep '/lib64' | grep -v -E 'libm.so|libstdc\+\+.so|libdl.so|libgcc_s.so|libc.so|ld-linux-x86-64.so|libpthread.so|librt.so|libz.so|libthread_db.so')
    if [ "${output}_" != "_" ]
    then
        echo $i:
        echo $output
    fi
done
```
prints:
```
/usr/lib/jvm/java-11-openjdk-11.0.9.11-9.fc33.x86_64/lib/libfontmanager.so:
        libfreetype.so.6 => /lib64/libfreetype.so.6 (0x00007f1a92bd6000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f1a925a7000)
        libpng16.so.16 => /lib64/libpng16.so.16 (0x00007f1a9256e000)
        libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007f1a92546000)
        libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007f1a92507000)
/usr/lib/jvm/java-11-openjdk-11.0.9.11-9.fc33.x86_64/lib/libjavajpeg.so:
        libjpeg.so.62 => /lib64/libjpeg.so.62 (0x00007f6f43b22000)
/usr/lib/jvm/java-11-openjdk-11.0.9.11-9.fc33.x86_64/lib/libjsound.so:
        libasound.so.2 => /lib64/libasound.so.2 (0x00007fc033bac000)
/usr/lib/jvm/java-11-openjdk-11.0.9.11-9.fc33.x86_64/lib/liblcms.so:
        liblcms2.so.2 => /lib64/liblcms2.so.2 (0x00007f30ca64a000)
```

Similarly on Ubuntu 20.04 running:
```shell
for i in $(dpkg -L openjdk-11-jre-headless | grep \\.so)
do
    output=$(ldd $i | grep '/x86_64' | grep -v -E 'libm.so|libstdc\+\+.so|libdl.so|libgcc_s.so|libc.so|ld-linux-x86-64.so|libpthread.so|librt.so|libz.so|libthread_db.so')
    if [ "${output}_" != "_" ]
    then
        echo $i:
        echo $output
    fi
done
```
prints:
```
/usr/lib/jvm/java-11-openjdk-amd64/lib/libawt_xawt.so:
libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007f523374f000) libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007f5233612000) libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007f5233408000) libXtst.so.6 => /lib/x86_64-linux-gnu/libXtst.so.6 (0x00007f52331fa000) libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x00007f52331e8000) libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f5232f7b000) libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007f5232f61000) libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f5232f59000) libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f5232f3d000)
/usr/lib/jvm/java-11-openjdk-amd64/lib/libfontmanager.so:
libfreetype.so.6 => /lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f217f7c8000) libpng16.so.16 => /lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f217f150000)
/usr/lib/jvm/java-11-openjdk-amd64/lib/libj2pcsc.so:
libpcsclite.so.1 => /lib/x86_64-linux-gnu/libpcsclite.so.1 (0x00007fdc71e6d000)
/usr/lib/jvm/java-11-openjdk-amd64/lib/libjavajpeg.so:
libjpeg.so.8 => /lib/x86_64-linux-gnu/libjpeg.so.8 (0x00007f59faa73000)
/usr/lib/jvm/java-11-openjdk-amd64/lib/libjawt.so:
libXext.so.6 => /lib/x86_64-linux-gnu/libXext.so.6 (0x00007fda7e979000) libX11.so.6 => /lib/x86_64-linux-gnu/libX11.so.6 (0x00007fda7e83c000) libXrender.so.1 => /lib/x86_64-linux-gnu/libXrender.so.1 (0x00007fda7e632000) libXtst.so.6 => /lib/x86_64-linux-gnu/libXtst.so.6 (0x00007fda7e424000) libXi.so.6 => /lib/x86_64-linux-gnu/libXi.so.6 (0x00007fda7e412000) libxcb.so.1 => /lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fda7e1a3000) libXau.so.6 => /lib/x86_64-linux-gnu/libXau.so.6 (0x00007fda7e18b000) libXdmcp.so.6 => /lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fda7e183000) libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007fda7e167000)
/usr/lib/jvm/java-11-openjdk-amd64/lib/libjsound.so:
libasound.so.2 => /lib/x86_64-linux-gnu/libasound.so.2 (0x00007f3bc6896000)
/usr/lib/jvm/java-11-openjdk-amd64/lib/liblcms.so:
liblcms2.so.2 => /lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007f901ce57000)
```

As a result:
1. The native image of applications that link against these libraries are not portable (i.e., they require the corresponding system libraries to be available on the deployment system at runtime). For instance one can not run the resulting native image on a [`ubi8-minimal` container image](https://catalog.redhat.com/software/containers/detail/5c64772edd19c77a158ea216).
2. Additionally some applications, e.g., applications that depend on `sun.java2d.cmm.lcms.LCMS`, require additional flags to be passed to the linker through the `-H:NativeLinkerOption` parameter, e.g., `-H:NativeLinkerOption="-llcms2"`.

## How To Reproduce
1. Build mandrel with `JAVA_HOME` set to the Fedora/Ubuntu OpenJDK installation
2. Build an application that depends on `sun.java2d.cmm.lcms.LCMS` (see https://github.com/oracle/graal/issues/3031 for an example)

### Configuration:
 - OS: Fedora 33 and Ubuntu 20.04
 - Architecture: AMD64
 - Mandrel version: 20.3.1.1.Final and 21.0.0.0.Final
 - JDK version: 11.0.10+9

## Expected behavior
1. Ideally native images would run on a [`ubi8-minimal` container image](https://catalog.redhat.com/software/containers/detail/5c64772edd19c77a158ea216) without the need to install additional dependencies.
2. Builds should not require `-H:NativeLinkerOption` in order to succeed.

## Aditional Info
This isn't an issue for upstream Mandrel builds, since the base OpenJDK use in-tree AWT libs. Therefore static libs produced during that build are self-contained in contrast to some OpenJDK builds part of Linux distributions.

**Comment by jerboaa** [comment]
I'm not sure why I'm assigned to this issue.

There is nothing we can do about that in mandrel as the JDK static-libraries come from the base JDK (OpenJDK) and one is at the mercy of the OpenJDK provider to build static-libs in a way so that intree AWT deps are being used (over system libraries). My proposal to do that for Fedora is here:
https://src.fedoraproject.org/rpms/java-11-openjdk/pull-request/109

So this issue showing up or not depends on how the base OpenJDK is being built and might need changes in the build process of *that* JDK. I'll leave this open until at least Fedora's OpenJDK is fixed. Once it's done, this shouldn't be an issue any more.

**Comment by zakkak** [comment]
> My proposal to do that for Fedora is here:
https://src.fedoraproject.org/rpms/java-11-openjdk/pull-request/109

The reason you are working on getting it fixed on Fedora is the reason why I assigned it to you :)

**Comment by jerboaa** [comment]
https://src.fedoraproject.org/rpms/java-11-openjdk/pull-request/111 has been merged. We'll wait for this fix to hit stable Fedora releases and we can close it after.

**Comment by zakkak** [comment]
@jerboaa it looks like the changes from https://src.fedoraproject.org/rpms/java-11-openjdk/pull-request/111 have been [pushed to F34](https://src.fedoraproject.org/rpms/java-11-openjdk/c/d6dfd5d5faa4572404a4251aca94c61dffa6f55e?branch=f34) and I can no longer reproduce the issue where we needed to add `-H:NativeLinkerOption="-llcms2"`.

Can you please verify and close this?

**Comment by jerboaa** [comment]
Yes, this is fixed. Closing.

**Comment by jerboaa** [comment]
With JDK 11.0.12 there should also be no issues with related to duplicate symbols. Fedora 33, 34 and lower build OpenJDK with `-fcommon` masking the issue. The `-fcommon` work-around has been removed since:
https://src.fedoraproject.org/rpms/java-11-openjdk/c/4b607408ff7cb8dc7177a74dac586af54b8a7069?branch=rawhide

OpenJDK bug which fixed this:
https://bugs.openjdk.java.net/browse/JDK-8264047
