### ISSUE TITLE
`graal/master` branch fails to build with latest OpenJDK 11.0.11 EA

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#214]
## Description
`graal/master` branch fails to build with latest OpenJDK EA, but builds fine with OpenJDK GA. The rest of the branches also build with both OpenJDKs.

```
Error: Could not find target method: private java.lang.invoke.MethodHandle com.oracle.svm.methodhandles.Target_java_lang_invoke_MethodHandles_Lookup.maybeBindCaller(com.oracle.svm.methodhandles.Target_java_lang_invoke_MemberName,java.lang.invoke.MethodHandle,java.lang.Class) throws java.lang.IllegalAccessException
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1651)
	at build.buildAgents(build.java:176)
	at build.main(build.java:159)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
	at OperatingSystem.exec(build.java:1642)
	at build.buildAgents(build.java:176)
	at build.main(build.java:159)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:404)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:179)
	at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:119)
```
See https://github.com/graalvm/mandrel/runs/1916200074?check_suite_focus=true#step:7:37

### Configuration:
 - OS: Fedora 33
 - Architecture: AMD64
 - Mandrel version: branch `graal/master`
 - JDK version:  11.0.11+2 EA build

## Expected behavior
It should build like it builds with OpenJDK GA

**Comment by zakkak** [comment]
Running the build with `--verbose` shows that the failure when building `native-image-agent-library`:
```
DEBUG [OperatingSystem] Execute [/tmp/mandrel-EA/lib/svm/bin/native-image, --macro:native-image-agent-library] in /home/zakkak/code/mandrel-packaging
```

The failure is triggered by the substitution [here](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.methodhandles/src/com/oracle/svm/methodhandles/Target_java_lang_invoke_MethodHandles_Lookup.java#L49-L57).

**Comment by zakkak** [comment]
The issue seems to be due to labs-openJDK-11 (and Graal) being out of sync with jdk11u-dev, the missing change is https://github.com/openjdk/jdk11u-dev/commit/806545796aed36a5adf34f344049d35a2313afe1#diff-32b33c7b5aa77e89f0218dc313bcdeb3edcc526ca6f5f9c31839f474d92a1d4bL2339-R2333

**Comment by zakkak** [comment]
The following patch fixes it (but breaks 11.0.10 builds).

```diff
diff --git a/substratevm/src/com.oracle.svm.methodhandles/src/com/oracle/svm/methodhandles/Target_java_lang_invoke_MethodHandles_Lookup.java b/substratevm/src/com.oracle.svm.methodhandles/src/com/oracle/svm/methodhandles/Target_java_lang_invoke_MethodHandles_Lookup.java
index 4afb2ed3834..37a61e766a3 100644
--- a/substratevm/src/com.oracle.svm.methodhandles/src/com/oracle/svm/methodhandles/Target_java_lang_invoke_MethodHandles_Lookup.java
+++ b/substratevm/src/com.oracle.svm.methodhandles/src/com/oracle/svm/methodhandles/Target_java_lang_invoke_MethodHandles_Lookup.java
@@ -34,9 +34,9 @@ import com.oracle.svm.core.annotate.RecomputeFieldValue;
 import com.oracle.svm.core.annotate.Substitute;
 import com.oracle.svm.core.annotate.TargetClass;
 import com.oracle.svm.core.annotate.TargetElement;
-import com.oracle.svm.core.jdk.JDK11OrEarlier;
-import com.oracle.svm.core.jdk.JDK15OrLater;
+import com.oracle.svm.core.jdk.JDK11OrLater;
 import com.oracle.svm.core.jdk.JDK16OrLater;
+import com.oracle.svm.core.jdk.JDK8OrEarlier;
 
 @TargetClass(value = MethodHandles.class, innerClass = "Lookup", onlyWith = MethodHandlesSupported.class)
 final class Target_java_lang_invoke_MethodHandles_Lookup {
@@ -48,7 +48,7 @@ final class Target_java_lang_invoke_MethodHandles_Lookup {
 
     @SuppressWarnings({"static-method", "unused"})
     @Substitute
-    @TargetElement(onlyWith = JDK11OrEarlier.class)
+    @TargetElement(onlyWith = JDK8OrEarlier.class)
     private MethodHandle maybeBindCaller(Target_java_lang_invoke_MemberName method, MethodHandle mh,
                     Class<?> boundCallerClass)
                     throws IllegalAccessException {
@@ -58,7 +58,7 @@ final class Target_java_lang_invoke_MethodHandles_Lookup {
 
     @SuppressWarnings({"static-method", "unused"})
     @Substitute
-    @TargetElement(onlyWith = JDK15OrLater.class)
+    @TargetElement(onlyWith = JDK11OrLater.class)
     private MethodHandle maybeBindCaller(Target_java_lang_invoke_MemberName method, MethodHandle mh,
                     Target_java_lang_invoke_MethodHandles_Lookup boundCaller)
                     throws IllegalAccessException {
```

**Comment by jerboaa** [comment]
So it's https://bugs.openjdk.java.net/browse/JDK-8235351in 11.0.11 which is causing it. It'll eventually trickle down to labs jdk. So there likely need to be version specific substitutions. One for 11.0.10 and earlier in the JDK 11 train and one for JDK 11.0.11+.

**Comment by zakkak** [comment]
> So there likely need to be version specific substitutions. One for 11.0.10 and earlier in the JDK 11 train and one for JDK 11.0.11+.

I am not sure it's worth it given that both the labs-openJDK and the OpenJDK will be on par for the 21.1 release.
But, let's better discuss this in [the email thread](https://oss.oracle.com/pipermail/graalvm-dev/2021-February/000100.html). Or feel free to open an upstream issue if you prefer to discuss it there.

**Comment by jerboaa** [comment]
> > So there likely need to be version specific substitutions. One for 11.0.10 and earlier in the JDK 11 train and one for JDK 11.0.11+.
> 
> I am not sure it's worth it given that both the labs-openJDK and the OpenJDK will be on par for the 21.1 release.
> But, let's better discuss this in [the email thread](https://oss.oracle.com/pipermail/graalvm-dev/2021-February/000100.html). Or feel free to open an upstream issue if you prefer to discuss it there.

So why would labsjdk based on 11.0.11 not run into it, though? Anyway I've filed an upstream issue. I hope it's OK that I took your fix and slightly adjusted it so it works with 11.0.10 and 11.0.11.

**Comment by zakkak** [comment]
> So why would labsjdk based on 11.0.11 not run into it, though?

It would, but at that point the fix from https://github.com/graalvm/mandrel/issues/214#issuecomment-781406547 could be applied and get that fixed. Since we don't anticipate anyone building newer GraalVM versions with outdated OpenJDK releases I just didn't think it's worth adding a check for <= 11.0.10 and >= 11.0.11. It looks like I was wrong though :)

> I hope it's OK that I took your fix and slightly adjusted it so it works with 11.0.10 and 11.0.11.

Yup, that's totally fine. Thanks for taking care of it!

**Comment by jerboaa** [comment]
> > So why would labsjdk based on 11.0.11 not run into it, though?
> 
> It would, but at that point the fix from [#214 (comment)](https://github.com/graalvm/mandrel/issues/214#issuecomment-781406547) could be applied and get that fixed. Since we don't anticipate anyone building newer GraalVM versions with outdated OpenJDK releases I just didn't think it's worth adding a check for <= 11.0.10 and >= 11.0.11. It looks like I was wrong though :)

I see. From past experience they want to keep backwards compatibility for building, which is somewhat understandable as you'd otherwise have to force every developer to use the latest base JDK for building (which includes gates/ci).

**Comment by jerboaa** [comment]
@zakkak Can we close this now or is it still an issue?

**Comment by jerboaa** [comment]
Fixed with: https://github.com/oracle/graal/commit/7d23c3aa6c7e8f2687a13ca4dbdea2d080687f26
