### ISSUE TITLE
Make a Windows build

### ISSUE THREAD

**Issue by maxandersen** [graalvm/mandrel#216]
**Is your feature request related to a problem? Please describe.**
similar to #114 but for Windows

**Describe the solution you'd like**
That we have a community available version of mandrel that runs and builds windows binaries.

**Comment by jerboaa** [comment]
@maxandersen I don't understand the issue. We have Windows Mandrel builds:
https://github.com/graalvm/mandrel/releases/tag/mandrel-20.3.1.2.Final

For example:
https://github.com/graalvm/mandrel/releases/download/mandrel-20.3.1.2.Final/mandrel-java11-windows-amd64-20.3.1.2.Final.zip

**Comment by maxandersen** [comment]
GAH. I missed those somehow. Then just close :)
