### ISSUE TITLE
Update readme to provide Mandrel information

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#25]
Add:
* communication channels
* what is Mandrel and how it compares to Graal
* other?

**Comment by zakkak** [comment]
I was thinking that we could use the wiki of this repo to avoid large diffs in the readme file.
This way we can keep all the info in our wiki and only add a few lines in the beginning of graal's readme redirecting users to the wiki.

The drawback with this is that part of the documentation won't be shipped with the code (e.g. when cloning the repo, or downloading a tag). WDYT?

**Comment by Karm** [comment]
@zakkak @galderz  I am +1 for a separate Mandrel README.md file that would capture what users need to know about Mandrel differences / dependencies etc.

I will amend the PR to create such a file shortly.

**Comment by jerboaa** [comment]
> I was thinking that we could use the wiki of this repo to avoid large diffs in the readme file.
> This way we can keep all the info in our wiki and only add a few lines in the beginning of graal's readme redirecting users to the wiki.
> 
> The drawback with this is that part of the documentation won't be shipped with the code (e.g. when cloning the repo, or downloading a tag). WDYT?

It would be good if a user could see the diffs directly in the release tarball without the need to find the wiki. Do we expect a potential `README-mandrel.md` to change much?

**Comment by galderz** [comment]
@jerboaa Hmmm, that's a good point. Things might evolve over time. How would the wiki accomodate that @zakkak?

**Comment by zakkak** [comment]
I think for now `README-mandrel.md` seems enough (thus the #38 PR).

Unfortunately the wiki leaves on a separate repository and needs to be maintained updated independently.
As a result we would need to add links to the wiki in our tarballs and the welcome page of the repository.
Depending on how much things we need to document in the future, a wiki or a readthedocs.io instance might become necessary.
Quarkus maintains its own website for documentation, but that's an overkill for Mandrel.

Considering that most documentation is shared between Graal and Mandrel it probably makes sense to update Graal's documentation (Readme files in different folders) where necessary and make them available in some web page (like graal does in https://www.graalvm.org/docs/Native-Image/user/README)
