### ISSUE TITLE
Create first community release

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#26]
We need to:
* tag latest commit in branch 20 (so we have to decide the tagging scheme we plan to follow)
* release a mandrel tarball

**Comment by ppalaga** [comment]
Builds for which platforms will be available?

**Comment by zakkak** [comment]
Hello @ppalaga, at the moment we are planning to release tarballs only for amd64

**Comment by zakkak** [comment]
Currently blocked by #38

**Comment by Xaseron** [comment]
Can you also provide a container image like https://hub.docker.com/r/oracle/graalvm-ce?

**Comment by Karm** [comment]
Hello @Xaseron,
there will be a Quarkus builder image based on Mandrel.
