### ISSUE TITLE
Incorrect file name for lambda methods in DWARF info of images generated with Mandrel 21.1

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#266]
## Description
Native images generated using `-g` and Mandrel 21.1 produce DWARF info files with wrong filename associations.

e.g.:
```
$ gdb -ex 'info functions .*smoke.*' debug-symbols-smoke-mandrel-21.1                      
Reading symbols from debug-symbols-smoke-mandrel-21.1...
All functions matching regular expression ".*smoke.*":

File debug_symbols_smoke/ClassA.java:
	java.lang.String *debug_symbols_smoke.ClassA::toString(void);

File debug_symbols_smoke/Main$$Lambda$547/0x00000007c0d0e440.java:
	void debug_symbols_smoke.Main$$Lambda$547.0x00000007c0d0e440::accept(java.lang.Object *);

File debug_symbols_smoke/Main.java:
	void debug_symbols_smoke.Main::lambda$thisIsTheEnd$0(java.io.ByteArrayOutputStream *, debug_symbols_smoke.ClassA *);
	void debug_symbols_smoke.Main::main(java.lang.String[] *);
	void debug_symbols_smoke.Main::thisIsTheEnd(java.util.List *);
```

Note the `debug_symbols_smoke/Main$$Lambda$547/0x00000007c0d0e440.java` file which does not really exist in the sources.

## How To Reproduce
1. `git clone https://github.com/Karm/mandrel-integration-tests.git`
2. `cd mandrel-integration-tests.git`
3. `mvn package -pl apps/debug-symbols-smoke`
3. `native-image -g -jar apps/debug-symbols-smoke/target/debug-symbols-smoke.jar debug-symbols-smoke-mandrel-21.1`
4. `gdb -ex 'info functions .*smoke.*' debug-symbols-smoke-mandrel-21.1`

### Configuration:
 - OS: Fedora 34
 - Architecture: AMD64
 - Mandrel version: 21.1.0.0-Final
 - JDK version: 11.0.11+9

## Expected behavior
`info functions .*smoke.*` should return:
```
All functions matching regular expression ".*smoke.*":

File debug_symbols_smoke/ClassA.java:
	java.lang.String *debug_symbols_smoke.ClassA::toString(void);

File debug_symbols_smoke/Main.java:
	void debug_symbols_smoke.Main$$Lambda$596/1305199729::accept(java.lang.Object *);
	void debug_symbols_smoke.Main::lambda$thisIsTheEnd$0(java.io.ByteArrayOutputStream *, debug_symbols_smoke.ClassA *);
	void debug_symbols_smoke.Main::main(java.lang.String[] *);
	void debug_symbols_smoke.Main::thisIsTheEnd(java.util.List *);
```

## Additional context
The corresponding GraalVM generated image seems to handle this properly.

```
$ gdb -ex 'info functions .*smoke.*' debug-symbols-smoke-graalvm-21.1 
Reading symbols from debug-symbols-smoke-graalvm-21.1...
All functions matching regular expression ".*smoke.*":

File debug_symbols_smoke/ClassA.java:
	java.lang.String *debug_symbols_smoke.ClassA::toString(void);

File debug_symbols_smoke/Main.java:
	void debug_symbols_smoke.Main$$Lambda$596/1305199729::accept(java.lang.Object *);
	void debug_symbols_smoke.Main::lambda$thisIsTheEnd$0(java.io.ByteArrayOutputStream *, debug_symbols_smoke.ClassA *);
	void debug_symbols_smoke.Main::main(java.lang.String[] *);
	void debug_symbols_smoke.Main::thisIsTheEnd(java.util.List *);
```

**Comment by zakkak** [comment]
This issue is due to https://bugs.openjdk.java.net/browse/JDK-8225810 not being back-ported to JDK 11.

It looks like we have two choices:
1. Backport only the changes in [MetaUtil.java](https://github.com/openjdk/jdk/commit/3b0ee5a6d8b89a52b0dacc51399955631d6aa597#diff-8392915f884c0b8e2ea110f25b7d50a7c5ccb5125d1bad085b4fd7077b8edc62)
2. Perform the `isJavaIdentifierStart` check in [SourceManager.computeBaseName()](https://github.com/oracle/graal/blob/91d8e9bff838274eb8c9941437f2d5b2078ac26b/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/image/sources/SourceManager.java#L97)

@jerboaa what do you think about 1?

**Comment by jerboaa** [comment]
@zakkak Seems like the best plan of action. Doing 2) would be a hard sell upstream as this doesn't happen with labs OpenJDK 11. Doing 1) seems fairly low risk as it's JVMCI self-contained. Do we have a test for this particular issue? It would be nice to have for a backport. I'll investigate a partial backport of JDK-8225810 and keep you posted.

**Comment by zakkak** [comment]
> Do we have a test for this particular issue?

For Mandrel we have a [test in mandrel-integration-tests](https://github.com/Karm/mandrel-integration-tests/tree/master/apps/debug-symbols-smoke/src/main/java/debug_symbols_smoke) which is [currently expecting the wrong output](https://github.com/Karm/mandrel-integration-tests/blob/9b414b43486b218c304575e86849f5d4ac6a9f3e/testsuite/src/it/java/org/graalvm/tests/integration/utils/GDBSession.java#L98), once we fix the issue we can make it expect the correct output as well.

For the backport I suggest using the following test.

I can reproduce the error using:
```java
import jdk.vm.ci.meta.MetaUtil;

public class Main {

    public static final String INTERNAL_NAME = "Ldebug_symbols_smoke/Main$$Lambda$547/0x00000007c0d0e440";
    public static final String EXPECTED_JAVA_NAME = "debug_symbols_smoke.Main$$Lambda$547/0x00000007c0d0e44";

    public static void main(String[] args) {
        int result = MetaUtil.internalNameToJava(INTERNAL_NAME, true, false).equals(EXPECTED_JAVA_NAME) ? 0 : 1;
        System.exit(result);
    }
}
```

**Comment by jerboaa** [comment]
> I can reproduce the error using:
> 
> ```java
> import jdk.vm.ci.meta.MetaUtil;
> 
> public class Main {
> 
>     public static final String INTERNAL_NAME = "Ldebug_symbols_smoke/Main$$Lambda$547/0x00000007c0d0e440";
>     public static final String EXPECTED_JAVA_NAME = "debug_symbols_smoke.Main$$Lambda$547/0x00000007c0d0e44";
> 
>     public static void main(String[] args) {
>         int result = MetaUtil.internalNameToJava(INTERNAL_NAME, true, false).equals(EXPECTED_JAVA_NAME) ? 0 : 1;
>         System.exit(result);
>     }
> }
> ```

Awesome, thanks! That'll do.

**Comment by Karm** [comment]
@zakkak Is there a version with which you would expect it to return 0 then?

```
mandrel-java11-21.2-SNAPSHOT
karm@localhost:~/tmp$ javac  --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp ~/workspaceRH/mandrel-release/mandrel-java11-21.2-SNAPSHOT/lib/jvmci/graal-sdk.jar MetaUtilTest.java 
karm@localhost:~/tmp$ java --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp ~/workspaceRH/mandrel-release/mandrel-java11-21.2-SNAPSHOT/lib/jvmci/graal-sdk.jar:. MetaUtilTest
1

mandrel-11.0.12.6_ea-0.vanilla.tagly.20.3.2.0_Final_1_gf9f24ba465
karm@localhost:~/tmp$ javac  --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp ~/workspaceRH/mandrel-release/mandrel-11.0.12.6_ea-0.vanilla.tagly.20.3.2.0_Final_1_gf9f24ba465/lib/jvmci/graal-sdk.jar MetaUtilTest.java 
karm@localhost:~/tmp$ java --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp ~/workspaceRH/mandrel-release/mandrel-11.0.12.6_ea-0.vanilla.tagly.20.3.2.0_Final_1_gf9f24ba465/lib/jvmci/graal-sdk.jar:. MetaUtilTest
1

graalvm-ce-java11-21.1.0
karm@localhost:~/tmp$ javac  --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp ~/X/JDKs/graalvm-ce-java11-21.1.0/lib/jvmci/graal-sdk.jar MetaUtilTest.java 
karm@localhost:~/tmp$ java --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp ~/X/JDKs/graalvm-ce-java11-21.1.0/lib/jvmci/graal-sdk.jar:. MetaUtilTest
1

graalvm-ce-java11-20.3.2
karm@localhost:~/tmp$ javac  --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp ~/X/JDKs/graalvm-ce-java11-20.3.2/lib/jvmci/graal-sdk.jar MetaUtilTest.java 
karm@localhost:~/tmp$ java --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp ~/X/JDKs/graalvm-ce-java11-20.3.2/lib/jvmci/graal-sdk.jar:. MetaUtilTest
1

graalvm-ce-java11-20.3.0
karm@localhost:~/tmp$ javac  --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp /home/karm/X/JDKs/graalvm-ce-java11-20.3.0/lib/jvmci/graal-sdk.jar MetaUtilTest.java 
karm@localhost:~/tmp$ java --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp /home/karm/X/JDKs/graalvm-ce-java11-20.3.0/lib/jvmci/graal-sdk.jar:. MetaUtilTest
1
```

**Comment by zakkak** [comment]
@Karm that's interesting. I get 0 on the last 3 GraalVM CE releases:

```shell
$ /opt/jvms/graalvm-ce-java11-21.1.0/bin/java --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED Main
$ echo $?
0

$ /opt/jvms/graalvm-ce-java11-21.0.0/bin/java --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED Main
$ echo $?
0

$ /opt/jvms/graalvm-ce-java11-20.3.2/bin/java --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED Main 
$ echo $?
0

$ /opt/jvms/mandrel-java11-21.1.0.0-Final/bin/java --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED Main
$ echo $?
1
```

**Comment by Karm** [comment]
@zakkak  Oh.  It was just my clumsiness. Sorry to bother you. Thanks for :duck:  debugging :-) 
I left the java and javac on PATH, just changing classpath...

```
karm@localhost:~/tmp$ export JAVA_HOME=~/workspaceRH/mandrel-release/mandrel-11.0.12.6_ea-0.vanilla.tagly.20.3.2.0_Final_1_gf9f24ba465/;export PATH=${JAVA_HOME}/bin:${PATH}
karm@localhost:~/tmp$ javac --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp ${JAVA_HOME}/lib/jvmci/graal-sdk.jar MetaUtilTest.java 
karm@localhost:~/tmp$ java --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp ${JAVA_HOME}/lib/jvmci/graal-sdk.jar:. MetaUtilTest
1
karm@localhost:~/tmp$ export JAVA_HOME=~/X/JDKs/graalvm-ce-java11-21.1.0/;export PATH=${JAVA_HOME}/bin:${PATH}
karm@localhost:~/tmp$ javac --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp ${JAVA_HOME}/lib/jvmci/graal-sdk.jar MetaUtilTest.java 
karm@localhost:~/tmp$ java --add-modules jdk.internal.vm.ci --add-exports jdk.internal.vm.ci/jdk.vm.ci.meta=ALL-UNNAMED -cp ${JAVA_HOME}/lib/jvmci/graal-sdk.jar:. MetaUtilTest
0
```

**Comment by jerboaa** [comment]
>     1. Backport only the changes in [MetaUtil.java](https://github.com/openjdk/jdk/commit/3b0ee5a6d8b89a52b0dacc51399955631d6aa597#diff-8392915f884c0b8e2ea110f25b7d50a7c5ccb5125d1bad085b4fd7077b8edc62)

See https://git.openjdk.java.net/jdk11u-dev/pull/120

**Comment by jerboaa** [comment]
Should be fixed with OpenJDK 11.0.13 (October 2021) and better:

https://bugs.openjdk.java.net/browse/JDK-8270196 (fix)
https://bugs.openjdk.java.net/browse/JDK-8270184 (regression test)

**Comment by jerboaa** [comment]
Note that current 11.0.13+2 EA builds have this fix.

**Comment by jerboaa** [comment]
I'm closing this issue as there is nothing on the mandrel side to do. OpenJDK fix is in place.
