### ISSUE TITLE
Introduce java 16 support

### ISSUE THREAD

**Issue by indiealexh** [graalvm/mandrel#267]
GraalVM 21.1.0 supports Java 16 and Quarkus compiles fine with Java 16. Adding java 16 support adds all the great features added in java 12 through 16 that make life easier in Java.

**Comment by indiealexh** [comment]
Would it be possible to have an ETA on this addition? Or maybe some guidance on how I can contribute this change myself?

**Comment by jerboaa** [comment]
@indiealexh Sorry, we don't have very much interest in JDK 16-based mandrel builds. JDK 16 is a short term support version and the last update (this July) was 16.0.2. Once JDK 17 is out this September, JDK 16 is obsolete. We are going to do JDK 17-based builds - on or around the GA date of JDK 17. JDK 17 expected to be the next long term support version of a JDK.

If you want to provide those builds yourself, you'd have to have a JDK 16 build with static-libs (plain OpenJDK 16), then build it using `mx` (preferably without actually jlinking a new JDK).

**Comment by jerboaa** [comment]
https://github.com/graalvm/mandrel/releases/tag/mandrel-21.3.0.0-Final

The latest mandrel 21.3 release includes JDK 17-based builds.
