### ISSUE TITLE
native-image version output is wrong for CI build of mandrel/20.3 marged with release/graal-vm/20.3

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#275]
CI merges https://github.com/oracle/graal/tree/release/graal-vm/20.3 with https://github.com/graalvm/mandrel/tree/mandrel/20.3 in this fashion: https://github.com/graalvm/mandrel-packaging/blob/master/jenkins/jobs/mandrel_graal_vm_20_3_linux_build.groovy#L109:L118

The resulting build produces a wrong version string:

```
$ ./native-image --version
20.3.2.1-dev9e62b46018 (Java Version 11.0.12-ea+6)

```

**Comment by zakkak** [comment]
This should now be fixed in https://github.com/graalvm/mandrel/tree/mandrel/20.3, and as a result in the merge result.
