### ISSUE TITLE
Only load harfbuzz as separate library for OpenJDK < 11.0.13

### ISSUE THREAD

**Issue by jerboaa** [graalvm/mandrel#286]
## Description
Since separation of the `libharfbuzz.so` OpenJDK library from `libfontmanager.so` caused regressions in OpenJDK 11. There in an attempt underway to revert this separation in OpenJDK 11.0.13. See:
https://bugs.openjdk.java.net/browse/JDK-8255790 and
https://bugs.openjdk.java.net/browse/JDK-8272149

Once the 11u backport of JDK-8255790 is resolved (currently targetting 11.0.13) the following commits should get conditionalized on specific OpenJDK versions:
https://github.com/oracle/graal/commit/9eb8b9efe9b8904165eb5b2e3d00e08ad9c7747c
https://github.com/oracle/graal/commit/2de5f6dedce3#diff-2968d71f5ee67eda096216019c513562666803c3d9a8ef6224de274df4ace586R87

**Comment by jerboaa** [comment]
Upstream PR: https://github.com/oracle/graal/pull/3738

**Comment by jerboaa** [comment]
Upstream PR got merged. We need to cherry-pick https://github.com/oracle/graal/commit/20e60c415985cb24efbdacf284ac7a5ebd9e49fe. But it may end up in the graal 21.3 release branch though. Aleksandar mentioned that during review.

**Comment by zakkak** [comment]
The commit got merged (as https://github.com/oracle/graal/commit/355600973b3b1eeebdcba4cc429e8a5e24bfb90a) on upstream 21.3 as well.
