### ISSUE TITLE
Previously passing configuration times out on GH actions

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#304]
## Description
mandrel 21.3-dev appears to be failing the last few days.

The last passing run was https://github.com/graalvm/mandrel/runs/3901801751?check_suite_focus=true with the following configuration:
| component | version | 
| --- | --- | 
| mandrel | 2d827b9970ac5e45dc1bb3e997aea4e3333d6939 |
| mandrel-packaging | 9bbf83a0a813c778762279faa0460661810ec554 |
| quarkus | a2c81efd6607d270dc7eaa9b7c38acb849c85030 |
| jdk | 11.0.13-ea+7 |
| mx | 5.309.2 |

Re-running the exact same configuration on GH runners results in timeouts or failures (see https://github.com/graalvm/mandrel/runs/3947878999?check_suite_focus=true)

## How To Reproduce
```
gh workflow run base.yml \
  -f quarkus-version=a2c81efd6607d270dc7eaa9b7c38acb849c85030 \
  -f name="rerun last working config for 21.3" \
  -f jdk=ea \
  -f version=2d827b9970ac5e45dc1bb3e997aea4e3333d6939 \
  -f mandrel-packaging-version=9bbf83a0a813c778762279faa0460661810ec554  
```

**Comment by jerboaa** [comment]
> Experimenting further I tried building GraalVM CE without libgraal and without jlinking [1], the results are the following:
> 	GraalVM CE 21.3 	Mandrel 21.3-dev 	GraalVM CE nolibgraal 	GraalVM CE nolibgraal nojlinking
> Comp time 	~16.5m 	~24.5m 	~15m 	~18.5m
> # of GCs 	275 	301 	245 	285
> # of Full GCs 	125 	153 	82 	113
> Time spend in Full GCs 	~11.5m 	~19.5m 	~9.8m 	~13.2m
> 
> Judging by the results it looks like not-jlinking has a big impact in the number of allocations.

This doesn't explain why we are seeing this now, though. Does it?

**Comment by zakkak** [comment]
FTR the commit that increased the memory usage and triggered the CI failures appears to be ce051011c6ae0d47a7a544065054c965705b14ba

It's also worth noting that trying `-H:-IncludeMethodData` (option added in ce051011c6ae0d47a7a544065054c965705b14ba) locally didn't have a big impact.

**Comment by zakkak** [comment]
I am closing this issue as my current understanding is that we were already stressing the JVM and https://github.com/graalvm/mandrel/commit/ce051011c6ae0d47a7a544065054c965705b14ba resulted in a small increase in memory usage that ended up consistently causing the CI runs to fail.

For the time being we have reverted Quarkus to using `-H:-ParseOnce` (see https://github.com/quarkusio/quarkus/pull/21018) to avoid the issue.

I plan to further investigate why `-H:+ParseOnce` has such a big impact in the case of Quarkus' `integration-tests/main`, see #316.
