### ISSUE TITLE
JDK 17 bf788eee880 and Mandrel 21.3 and 22.0

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#330]
# 21.3

JDK17u [bf788eee880](https://github.com/adoptium/jdk17u/commit/bf788eee880) discussed here: [3837](https://github.com/oracle/graal/issues/3837) is still breaking [mandrel/21.3](https://github.com/graalvm/mandrel/tree/mandrel/21.3) (rebased to `release/graal-vm/21.3`)
Do we backport [7992567](https://github.com/oracle/graal/commit/7992567acbd463e4fd80b9134833b74e94a3b4ca)?

```
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError:
com.oracle.svm.hosted.substitute.DeletedElementException: 
Unsupported method java.lang.ref.Reference.refersToImpl(Object) is reachable: 
The declaring class of this element has been substituted, but this element is not present in the substitution class
```

~~# 22.0~~
~~Mandrel 22.0, i.e. `mandrel/22.0` rebased to `release/graal-vm/22.0` has the same problem though, despite the fact the commit is in it.~~

**EDIT:**
**22.0** is O.K., as @jerboaa pointed out, the patch needs to be able to correctly detect the JDK version. My homemade build was reporting unusable version string `17-internal+0-adhoc.tester.jdk17 `.   I fixed that with `--with-version-feature=17 --with-version-interim=0 --with-version-update=2` and all is well with 22.0 branch all the way up to the current JDK 17 commit [aa11a935](https://github.com/adoptium/jdk17u/commit/aa11a935). So it's just 21.3 missing the patch, likely a backport candidate....

**Comment by jerboaa** [comment]
Please post version output of the JDK 17 in use.

**Comment by Karm** [comment]
@jerboaa I'm en route now. The JDK 17 version used is my own build of  bf788eee880. Will post the version output later.

**Comment by Karm** [comment]
@jerboaa  THX for the hint about version string. Description updated. 22.0 is fine.

**Comment by jerboaa** [comment]
@Karm Pretty sure it'll be part of `21.3.1` as there will be a JDK 17 build with it and OpenJDK 17.0.2 has the patch which requires the fix. So Graal CE will need it too.

**Comment by zakkak** [comment]
https://github.com/oracle/graal/commit/7992567acbd463e4fd80b9134833b74e94a3b4ca is indeed backported to 21.3.1 as https://github.com/oracle/graal/commit/6f3672c4045fa1e3e013c8832b13550037f456e7

**Comment by Karm** [comment]
Resolved.
