### ISSUE TITLE
Mandrel-specific issues

### ISSUE THREAD

**Issue by galderz** [graalvm/mandrel#36]
This is an umbrella issue to track all issues discovered in Quarkus and other projects that are Mandrel specific. That means, they are issues that are due to specific differences in Mandrel vs Oracle's GraalVM. 

One such difference is the underlying JVM, which in Mandrel's case is OpenJDK 11, whereas for Oracle's GraalVM that is [Labs JDK](https://github.com/graalvm/labs-openjdk-11).

Issues fixed so far:

* Camel AWS - com.sun.xml.internal.bind.v2.ContextFactory not found - https://github.com/quarkusio/quarkus/issues/7914
* NoClassDefFoundError for Spring - https://github.com/quarkusio/quarkus/issues/8081
* NoClassDefFoundError for Apache Tika and Open XML Formats - https://github.com/quarkusio/quarkus/issues/8081

Issues open:
* Reactive PG client NPE - https://github.com/graalvm/mandrel/issues/22 (@galderz working on a reproducer)

**Comment by galderz** [comment]
Another issue open:

* NoClassDefFoundError for Camel Olingo - https://github.com/apache/camel-quarkus/issues/1319

**Comment by Karm** [comment]
@galderz 

Quarkus 1.5 is passing with Mandrel 20.1 openjdk-11.0.8+4 ea with these exclusions for me:


*Took 2 hr 57 min on karm-centos8-x86-64*
  *3,369 tests (±0)*

```
export MODULES="-pl \
!devtools/aesh,\
!devtools/gradle,\
!docs,\
!integration-tests/devmode,\
!integration-tests/hibernate-orm-panache-kotlin,\
!integration-tests/smallrye-graphql"

./mvnw verify --fail-never --batch-mode -DfailIfNoTests=false -Pnative-image ${MODULES}
```

I will be getting to those failures shortly...

**Comment by galderz** [comment]
@Karm Please post links to the failure here.

**Comment by zakkak** [comment]
FYI we could possibly automate the tracking of issues reported in this issue using https://github.com/marketplace/actions/epic-issues-for-github

**Comment by galderz** [comment]
@zakkak Sounds good. Shall we just create a new workflow in https://github.com/graalvm/mandrel/tree/master/.github/workflows to support this?

**Comment by zakkak** [comment]
Yes that would be one way to do it, the other is adding it to https://github.com/graalvm/mandrel/blob/master/.github/workflows/repo-sync.yml since running it daily is probably OK.

**Comment by zakkak** [comment]
It looks like it doesn's support cross-repository issues (yet)
https://github.com/cloudaper/epics-action/issues/2

**Comment by galderz** [comment]
Oh bugger, that's a pity. Let's wait for that?
