### ISSUE TITLE
JDK-8275703 in OpenJDK 11.0.15+6 breaks build

### ISSUE THREAD

**Issue by jerboaa** [graalvm/mandrel#368]
**Describe the issue**
Building the latest 21.3 release branch with `OpenJDK 11.0.15+6` (EA) currently fails with:
```
[libnative-image-agent:38292]        setup:     485.35 ms,  0.96 GB
Error: Could not find target method: private native boolean com.oracle.svm.core.jdk.Target_java_lang_ClassLoader_NativeLibrary.load0(java.lang.String,boolean)
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
[libnative-image-agent:38292]      [total]:   1,392.59 ms,  0.96 GB
# Printing build artifacts to: [...]lib/svm/macros/native-image-agent-library/../../../libnative-image-agent.build_artifacts.txt
Error: Image build request failed with exit status 1
```

**More details**
https://bugs.openjdk.java.net/browse/JDK-8275703 adds a new 3-arg `load0` native method in `ClassLoader.NativeLibrary` which has been backported to OpenJDK 11.0.15 (to be released in April 2022). This is fixed in master with https://github.com/oracle/graal/commit/7ba248aa70de25ec78c1a5b82373a499f326d9bc

Upstream issue: https://github.com/oracle/graal/issues/4396

**Comment by jerboaa** [comment]
@Karm @zakkak Merging in the latest release/graal-vm/21.3 branch should fix this. Do you want we to prepare that?

**Comment by zakkak** [comment]
> @Karm @zakkak Merging in the latest release/graal-vm/21.3 branch should fix this. Do you want we to prepare that?

I will prepare a PR merging upstream 21.3 in mandrel's 21.3 branch which will allow our CI to run on it. I will not merge it though until later since there is high change more changes will come in the following weeks.

**Comment by jerboaa** [comment]
> > @Karm @zakkak Merging in the latest release/graal-vm/21.3 branch should fix this. Do you want we to prepare that?
> 
> I will prepare a PR merging upstream 21.3 in mandrel's 21.3 branch which will allow our CI to run on it. I will not merge it though until later since there is high change more changes will come in the following weeks.

OK, sounds good. Thanks!

**Comment by Karm** [comment]
Resolved.
