### ISSUE TITLE
07543988774cc46b0e2e9352f730968ace302d51 breaks compatibility with upstream OpenJDK 11

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#373]
## Description
07543988774cc46b0e2e9352f730968ace302d51 overrides `getAddress` and `getEntryPoint` in substratevm/src/com.oracle.svm.graal/src/com/oracle/svm/graal/meta/SubstrateInstalledCodeImpl.java, but these methods are `final` in upstream OpenJDK 11.

The `final` keyword was removed in OpenJDK 13 with [JDK-8220623](https://bugs.openjdk.java.net/browse/JDK-8220623) and is not backported to OpenJDK 11 causing GraalVM to fail to build.

See https://github.com/graalvm/mandrel/runs/6000866138?check_suite_focus=true#step:7:430

### Configuration:
 - OS: Fedora 35
 - Architecture: AMD64,
 - Mandrel version: 07543988774cc46b0e2e9352f730968ace302d51
 - JDK version: OpenJDK 11.0.14.1+1

## Expected behavior
Mandrel should build with upstream OpenJDK 11

**Comment by zakkak** [comment]
@jerboaa I think the best way to resolve this is by backporting [JDK-8220623](https://bugs.openjdk.java.net/browse/JDK-8220623)  (or maybe just the `final` keyword removal to OpenJDK 11u). 

Alternatively we can work-around this on the GraalVM side, by overriding the methods only when using JDK 17. But that doesn't look like an actual fix.

WDYT?

**Comment by jerboaa** [comment]
> @jerboaa I think the best way to resolve this is by backporting [JDK-8220623](https://bugs.openjdk.java.net/browse/JDK-8220623) (or maybe just the `final` keyword removal to OpenJDK 11u).
> 
> Alternatively we can work-around this on the GraalVM side, by overriding the methods only when using JDK 17. But that doesn't look like an actual fix.
> 
> WDYT?

Backporting [JDK-8220623](https://bugs.openjdk.java.net/browse/JDK-8220623) in its entirety is unfortunately not on the table. It's way to risky to backport to a stable release. We could consider a partial backport. I'll do some digging later today...

**Comment by jerboaa** [comment]
I've filed this OpenJDK issue for it:
https://bugs.openjdk.java.net/browse/JDK-8285395

**Comment by jerboaa** [comment]
This should be fixed once `11.0.16+1` EA builds become available.

**Comment by jerboaa** [comment]
Latest ea build from temurin should have this fixed. For example `OpenJDK11U-jdk_x64_linux_hotspot_2022-05-11-07-22.tar.gz`

**Comment by zakkak** [comment]
Confirmed (see https://github.com/graalvm/mandrel/runs/6388571079?check_suite_focus=true)

Thanks for the heads up @jerboaa
