### ISSUE TITLE
mandrel-java17-22.1.0.0-Final not working on windows when installed under a path containing spaces.

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#386]
## Description
$title

See https://github.com/quarkusio/quarkus/issues/25927 for more details

### Configuration:
 - OS: Windows 10
 - Architecture: AMD64
 - Mandrel version: 22.1.0.0-Final
 - JDK version: `17`

**Comment by jerboaa** [comment]
Graal VM CE ships with a native native-image launcher. Could be a source of difference. Either way, we should be able to catch this in the future with an integration test.

**Comment by Karm** [comment]
This occurred in the past already and was fixed, so this is a regression in what we do in the launcher. I had problems with it while doing https://github.com/graalvm/mandrel-packaging/pull/71 way back in the day.
Why haven't we caught it:

 * tests run either in `C:\tmp\` or
 * it gets installed in `C:\Program_Files'`  as created by `New-Item -ItemType SymbolicLink -path 'C:\Program_Files' -Target 'C:\Program Files' -Force` :disappointed: 

Assigning to me to fix the launcher and to fix the test.

**Comment by zakkak** [comment]
The fix is now merged upstream and [included in the upcoming 22.2 release](0da6c3554966c46551fed428f43d5e93262f102c), it will also be [backported to 21.3.3](https://github.com/oracle/graal/issues/4636).
