### ISSUE TITLE
Should we remove Graal's tags from Mandrel repo?

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#42]
When visiting https://github.com/graalvm/mandrel/releases users see Graal's tags, while I think we would like them to see only Mandrel tags.

Is there any use of the Graal tags in Mandrel? Can we remove them?

**Comment by Karm** [comment]
We are not going to be needing them here, so I would advocate for removing them for the sake of clarity.

**Comment by zakkak** [comment]
Graal tags are now removed.
