### ISSUE TITLE
Stop building JDK 11 based Mandrel builds

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#423]
As of https://github.com/quarkusio/quarkus/pull/26319 (released with Quarkus 2.11.0.Final) Quarkus has been defaulting to JDK-17 based builder images with no major issues so far. 

As a result we could phase out our JDK-11 builds and focus solely on the JDK-17 ones.

**Comment by zakkak** [comment]
cc @jerboaa @galderz @Karm

**Comment by jerboaa** [comment]
Yes, I agree (for latest master, releases). We need to keep them for 21.3.

**Comment by Karm** [comment]
I will gradually disable those builds on Jenkins instances for 22.3 and master.
