### ISSUE TITLE
Mandrel 21.3.4 <-> GraalVM 21.3.3.1 ?

### ISSUE THREAD

**Issue by rquinio1A** [graalvm/mandrel#451]
Hello,

I was looking for the Mandrel version for the OpenJDK October 2022 patch.
Upstream it's 21.3.4 https://docs.oracle.com/en/graalvm/enterprise/21/docs/release-notes/ 

There's already a Mandrel 21.3.4.0 but if I'm not mistaken it seems based off GraalVM 21.3.3.1 (OpenJDK 11.0.16) ? 
cf https://github.com/graalvm/mandrel/compare/mandrel-21.3.3.0-Final...mandrel-21.3.4.0-Final

Is there a new patch planned ?

**Comment by jerboaa** [comment]
Yes, we have tagged `21.3.4.0-Final` for the October 2022 CPU update which also syncs up with the 21.3.3.1 release from GraalVM. I don't know if there are any plans for GraalVM CE to make their tags for 21.3.4 public. I think they stop doing public CE updates once the next LTS is released which happened with 22.3.0 being released now. It's not yet clear whether or not we actually do the release. We'll keep you posted.

**Comment by zakkak** [comment]
> I don't know if there are any plans for GraalVM CE to make their tags for 21.3.4 public.

I confirm that there are no plans for a GraalVM CE 21.3.4 release

> Is there a new patch planned ?

Hello @rquinio1A may I ask what's your use case?

Mandrel releases are specifically tailored to Quarkus. Using 21.3 would only make sense if you are still using Quarkus 2.7. Are you?

If not, but you are interested in using an LTS Mandrel release, 22.3 just got out and Quarkus will soon switch to using GraalVM/Mandrel 22.3 (see https://github.com/quarkusio/quarkus/pull/28861)

**Comment by rquinio1A** [comment]
@jerboaa Thanks for the info
@zakkak Indeed we're using RHBQ 2.7.

**Comment by jerboaa** [comment]
> @zakkak Indeed we're using RHBQ 2.7.

Hmm, if you are using RHBQ 2.7 you should be on 21.3.4 (and OpenJDK 11.0.17/17.0.5) already when using the default images of the product code.

```
$ podman run --rm -ti registry.access.redhat.com/quarkus/mandrel-21-rhel8:21.3 --version
native-image 21.3.4.0-1b2 Mandrel Distribution (Java Version 11.0.17+8-LTS)
```

**Comment by jerboaa** [comment]
21.3.4.0 upstream release is here:
https://github.com/graalvm/mandrel/releases/tag/mandrel-21.3.4.0-Final
