### ISSUE TITLE
Java19 target support for Mandrel builds

### ISSUE THREAD

**Issue by anbonifacio** [graalvm/mandrel#460]
**Is your feature request related to a problem? Please describe.**
We have some Quarkus microservices built with <maven.compiler.target>18</maven.compiler.target> and would like to experiment with the generation of native code.
GraalVM 22.3 already has a release with Java 19 enabled, but Mandrel 22.3.x only supports Java 17 as a target.

**Describe the solution you'd like**
A distribution of Mandrel 22.3 that can build services with Java 18 target.

**Describe alternatives you've considered**
Using GraalVM 22.3

**Additional context**
-

**Comment by zakkak** [comment]
Hi @anbonifacio ,

At the moment, there are no plans for releasing 22.3.x with any version other than Java 17.

Note however that for 23.x we have not decided yet on which java version(s) it will be based.

For the time being, as you said, using GraalVM Java 19 builds is the only alternative.
