### ISSUE TITLE
Start testing Java 20 based mandrel builds for the next release

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#463]
**Is your feature request related to a problem? Please describe.**
The next GraalVM release (called GraalVM for Java 20) will be based solely on Java 20, there will be no Java 17 based release for it. Ideally Mandrel should follow the same approach so we should start testing this scenario.

**Describe the solution you'd like**
Add a CI job to the matrix to test Mandrel built with JDK 20.

**Comment by Karm** [comment]
Some logs: https://ci.modcluster.io/view/Mandrel/job/mandrel-master-aarch64-perf/JDK_RELEASE=ea,JDK_VERSION=20,LABEL=perf_baremetal_aarch64/

(it is a throwaway experimental job that tested our new aarch64 resources)
