### ISSUE TITLE
Removal of `oracle-*` branches?

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#50]
Following #40 to be consistent I suggest we rename `oracle-*` branches to `graal/*` e.g. `graal/master`.

Given the opportunity I would also like to ask whether anyone sees any value in keeping these branches around.
It looks like we don't do anything with them. If that's true removing them would make the repo much cleaner.

**Comment by Karm** [comment]
I am not using them. When I need oracle/graal I just use another remote...

**Comment by zakkak** [comment]
`oracle-*` branches are now removed.
