### ISSUE TITLE
Mandrel cannot dynamically load awt shared libraries from OpenJDK distro #487 

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#519]
JDK-20 specific tracker for https://github.com/graalvm/mandrel/issues/487

The issue should be fixed with the JDK 20 July CPU release.

**Comment by jerboaa** [comment]
https://bugs.openjdk.org/browse/JDK-8304871 is fixed for 20.0.2 which will be used as (one) base JDK for the 23.0.1 release. Closing as there is nothing more do do on the mandrel end. Lets reopen if we determine otherwise.
