### ISSUE TITLE
[23.0] backport tracker for JDK 11+ compatibility of org.graalvm.sdk:graal-sdk

### ISSUE THREAD

**Issue by jerboaa** [graalvm/mandrel#525]
Mandrel 23.0 tracker of a fix for https://github.com/oracle/graal/issues/6831

Proposed fix is [here](https://github.com/jerboaa/graal/commit/98069bb679e1544fd9f5d5125785a56029a19281) if it doesn't make it into a 23.0 update upstream.

**Comment by jerboaa** [comment]
Merged upstream master with https://github.com/oracle/graal/pull/6949/ and I'm told it'll land in 23.0 as well.

**Comment by zakkak** [comment]
Closed by https://github.com/graalvm/mandrel/pull/533
