### ISSUE TITLE
Mandrel master build failure (across JDK versions)

### ISSUE THREAD

**Issue by Karm** [graalvm/mandrel#531]
>  java.lang.module.FindException: Module org.graalvm.truffle.runtime not found, required by org.graalvm.nativeimage.driver

I suspect a Truffle dependency was reintroduced and we need to adjust Mandrel Packaging.

**Comment by Karm** [comment]
(Not sure if @zakkak has already worked on it, I wasn't up to date the past couple of days)

**Comment by zakkak** [comment]
No, that's fairly new! I will have a look.
