### ISSUE TITLE
Mandrel builds based on JDK 21+32 fail to compile native images with JFR monitoring enabled

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#546]
## Description
Mandrel builds based on JDK 21+32 fail to compile native images with JFR monitoring enabled due to:

```
[1/8] Initializing...                                                                                    (0.0s @ 0.10GB)
Error: Could not find target method: com.oracle.svm.core.jfr.Target_jdk_jfr_internal_EventWriter(long,long,long,long,boolean,boolean)
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
```

The constructor being substituted was altered in https://bugs.openjdk.org/browse/JDK-8303134

## How To Reproduce
1. Build mandrel using JDK 21+32
2. `native-image --enable-monitoring=jfr HelloWorld`

### Configuration:
 - OS: **Fedora 38**
 - Architecture: **AMD64**
 - Mandrel version: **95ac31139c6dbe392f4749654cecae6ae40043a9**
 - JDK version: **21+32**

## Expected behavior
The build should complete without errors

cc @roberttoyonaga

**Comment by roberttoyonaga** [comment]
Thanks @zakkak I'll work on fixing this

**Comment by roberttoyonaga** [comment]
@zakkak Should we close this issue now? It's been resolved for jdk21. See here: https://github.com/oracle/graal/pull/7070#issuecomment-1677880757

**Comment by jerboaa** [comment]
Closing as fixed. See https://github.com/oracle/graal/issues/7052#issuecomment-1682505809
