### ISSUE TITLE
Add changelog to Mandrel releases?

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#55]
Mandrel releases need a way to describe how they differ from the corresponding GraalVM CE release.
One way is using github's diff but a more human friendly approach would be to include a Changelog describing at least the core differences at high level.

Thoughts?

**Comment by Karm** [comment]
@zakkak +1 for the general concept, but we have to find a way to generate the file automatically.
I suggest a manifest / BOM like text file listing 
 + added commits on top of Graal's 20.1.0
 + OpenJDK version update, i.e. not just "11.0.8-ea", but the full "11.0.8-ea+7"

Perhaps taking advantage of GitHub Milestones, e.g. https://github.com/graalvm/mandrel/milestone/1 could facilitate the task.  For example, upgrading to  "11.0.8-ea+8" would have a GitHub issue assigned to the Milestone 20.1.0.0.Alpha2, trivially enabling us to generate "20.1.0.0.Alpha2" changelog...   IMHO.

**Comment by zakkak** [comment]
I don't have experience with using GH milestones but sounds good.

**Comment by zakkak** [comment]
I have manually added a changelog to 20.1.0.2.Final and the upcoming releases will feature one generated by https://github.com/graalvm/mandrel-packaging/blob/master/release-scripts/mandrel-release.java#L529
