### ISSUE TITLE
Windows CI failure due to missing `pigz`

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#560]
Windows workflows recently started failing with

```
/bin/sh: 1: pigz: not found
tar: maven-repo.tgz: Cannot write: Broken pipe
tar: Child returned status 127
tar: Error is not recoverable: exiting now
Error: Process completed with exit code 2.
```

See https://github.com/graalvm/mandrel/actions/runs/6074123813/job/16508072527#step:8:2

More details about `pigz` getting removed in https://github.com/actions/runner-images/issues/8161.

The issue is already fixed upstream in https://github.com/actions/runner-images/pull/8209, we just need for the updated runners to get deployed.

**Comment by jerboaa** [comment]
Looks good again:
https://github.com/graalvm/mandrel/actions/runs/6108691041/job/16578198310?pr=561#step:8:2
