### ISSUE TITLE
[CI] Quarkus main fails with Java 21 mandrel build of mandrel/23.1 on Windows

### ISSUE THREAD

**Issue by jerboaa** [graalvm/mandrel#562]
Automatic issue reporting for mandrel 23.1 windows.

Q main M 23.1 windows / Q IT

**Comment by jerboaa** [comment]
Caused by a quarkus build failure tracked in: https://github.com/quarkusio/quarkus/issues/40213

**Comment by zakkak** [comment]
Tracked in https://github.com/graalvm/mandrel/issues/732

**Comment by jerboaa** [comment]
Tracked in https://github.com/graalvm/mandrel/issues/732

**Comment by jerboaa** [comment]
Tracked in https://github.com/graalvm/mandrel/issues/732

**Comment by zakkak** [comment]
Fixed by https://github.com/graalvm/mandrel/pull/738
