### ISSUE TITLE
[23.1] Backport: Fix native-image build with --no-jlinking

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#585]
## What would you like to backport?
https://github.com/oracle/graal/pull/7205

## Why?
To get the same upstream patch in our release instead of using [our own](https://github.com/graalvm/mandrel/commit/588ae3a38d6d047ae30277f5fdd3e26d3cefada4).

## Are the changes being backported merged in upstream Graal?

- [x] Yes
- [ ] No

**Comment by jerboaa** [comment]
The 24.0 change depends on https://github.com/oracle/graal/pull/7454 so if we are going to backport https://github.com/oracle/graal/pull/7205 verbatim, we need to backport https://github.com/oracle/graal/pull/7454 first.

**Comment by zakkak** [comment]
@jerboaa, given the size and touch-area of https://github.com/oracle/graal/pull/7454 I am thinking about sticking to our original backport in 588ae3a38d6d047ae30277f5fdd3e26d3cefada4. WDYT?

**Comment by jerboaa** [comment]
> @jerboaa, given the size and touch-area of [oracle#7454](https://github.com/oracle/graal/pull/7454) I am thinking about sticking to our original backport in [588ae3a](https://github.com/graalvm/mandrel/commit/588ae3a38d6d047ae30277f5fdd3e26d3cefada4). WDYT?

@zakkak Given that `23.1` will likely stick around for a longer time, it would be best to backport it (IMO). It gets rid of a `java --list-modules` call which isn't great currently in 23.1. The earlier we can get it in the 23.1 cycle, the better.

**Comment by jerboaa** [comment]
I can do the backport if you like.

**Comment by zakkak** [comment]
> I can do the backport if you like.

Sure, please go ahead, since you are more familiar with the code there are more chances of getting it right before me :)

You should have push rights to https://github.com/zakkak/mandrel/tree/2023-12-18-23.1-jan-cpu-backports (https://github.com/graalvm/mandrel/pull/640) by the way (if you want to include it to the existing PR).

**Comment by jerboaa** [comment]
> > I can do the backport if you like.
> 
> Sure, please go ahead, since you are more familiar with the code there are more chances of getting it right before me :)

OK.

> You should have push rights to https://github.com/zakkak/mandrel/tree/2023-12-18-23.1-jan-cpu-backports (#640) by the way (if you want to include it to the existing PR).

Thanks, but I'll create a separate PR. It's a lot easier to review.

**Comment by jerboaa** [comment]
Fixed with https://github.com/graalvm/mandrel/pull/651
