### ISSUE TITLE
Native-image: Support -XX:+HeapDumpOnOutOfMemoryError

### ISSUE THREAD

**Issue by turing85** [graalvm/mandrel#593]
If we build a native-image with `--enable-monitoring=heapdump` and start the native-image with `... -XX:+HeapDumpOnOutOfMemoryError ...` the process terminates with the error message:
```
error: Could not find option 'HeapDumpOnOutOfMemoryError'. Did you mean one of these: ExitOnOutOfMemoryError. Use -XX:PrintFlags= to list all available options.
```
It would be nice if this feature was supported to analyze out of memory errors.

**Comment by galderz** [comment]
@turing85 `-XX:+HeapDumpOnOutOfMemoryError` is available starting with Mandrel 23.1 (GraalVM for JDK 21). https://github.com/oracle/graal/pull/7012

**Comment by jerboaa** [comment]
So feel free to grab a release from https://github.com/graalvm/mandrel/releases/tag/mandrel-23.1.0.0-Final and try that out.

**Comment by turing85** [comment]
@jerboaa are there plans for a backport to `23.0`? Not everyone is able to upgrade to java 21 right away.

**Comment by jerboaa** [comment]
@turing85 You could build your application with JDK `X` - where `11 <= X < 21` and run the native compilation with mandrel `23.1`, no?

**Comment by turing85** [comment]
@jerboaa not really. Customer policy is to only use red hat images (this includes the builder images in pipeline jobs). There is no `mandrel-23.1`-based red hat image. There is, however, a `mandrel-23.0`-based red hat image.

**Comment by turing85** [comment]
Scratch my last comment, there is a `mandrel -23.1`-base image.

**Comment by zakkak** [comment]
> Scratch my last comment, there is a `mandrel -23.1`-base image.

@turing85 beware that this would be an upstream mandrel image though, not a ["Red Hat Build of Quarkus Native builder"](https://catalog.redhat.com/software/containers/search?q=Red%20Hat%20build%20of%20Quarkus%20Native%20builder).

**Comment by turing85** [comment]
@zakkak I know, thanks for the heads-up :slightly_smiling_face:

**Comment by zakkak** [comment]
For future reference (i.e. people reaching here from google search) please note that the upstream mandrel-23.1 image is not compatible with (Red Hat Build of) Quarkus 3.2.
