### ISSUE TITLE
GraalVM master fails to build with OpenJDK 21 after GR-49610

### ISSUE THREAD

**Issue by jerboaa** [graalvm/mandrel#598]
## Description
GraalVM master fails to build with OpenJDK 21 with the Mandrel config after https://github.com/oracle/graal/pull/7650 with:

```
DEBUG [build] Build native agents...
DEBUG [OperatingSystem] Execute [/disk/graal/upstream-sources/graal/mandrel-build/lib/svm/bin/native-image, --macro:native-image-agent-library] in /disk/graal/upstream-sources/mandrel-packaging with environment variables []
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Module jdk.graal.compiler does not read a module that exports jdk.vm.ci.services
Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: Failed, exit code: 1
    at OperatingSystem.exec(build.java:1819)
    at build.buildAgents(build.java:310)
    at build.main(build.java:253)
Caused by: java.lang.RuntimeException: Failed, exit code: 1
    at OperatingSystem.exec(build.java:1808)
    at build.buildAgents(build.java:310)
    at build.main(build.java:253)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
    at jdk.compiler/com.sun.tools.javac.launcher.Main.execute(Main.java:484)
    at jdk.compiler/com.sun.tools.javac.launcher.Main.run(Main.java:208)
    at jdk.compiler/com.sun.tools.javac.launcher.Main.main(Main.java:135)
```

The corresponding OpenJDK bug is:
https://bugs.openjdk.org/browse/JDK-8318027

OpenJDK 21 would need a patch [like this one](https://github.com/jerboaa/jdk21u/commit/27ef7217dc92fd9e0b99be94d4d72141ff9a1708) in order to be able to continue to build GraalVM master with OpenJDK 21. JDK-8318027 fixes this for OpenJDK 22.

**Comment by zakkak** [comment]
@jerboaa have you tried requesting comments for https://github.com/jerboaa/jdk21u/commit/27ef7217dc92fd9e0b99be94d4d72141ff9a1708 from the jdk21u project reviewers?

I have toyed a bit with @adinn's idea of defining a proxy `jdk.internal.vm.compiler` module but haven't got anything remotely working yet (`mx` refuces to build my module).

**Comment by jerboaa** [comment]
> @jerboaa have you tried requesting comments for [jerboaa/jdk21u@27ef721](https://github.com/jerboaa/jdk21u/commit/27ef7217dc92fd9e0b99be94d4d72141ff9a1708) from the jdk21u project reviewers?

No I have not. Is this something critical to have in JDK 21? I don't think it is (as of yet).

**Comment by zakkak** [comment]
No, I do not think it's critical either (at least for the time being).

For the users relying on an LTS JDK we can keep building Mandrel 23.1 from https://github.com/graalvm/graalvm-for-jdk21-community-backports

This is expected to leave those users without access to more recent GraalVM features and improvements that might not be accepted for a backport in GraalVM for JDK 21. In this case the users will need to wait until the Mandrel 25.1 release (September 2025) which is planned to be built on top of the LTS JDK 25. This is also aligned with the upstream OpenJDK release cadence.

**Comment by jerboaa** [comment]
> No, I do not think it's critical either (at least for the time being).
> 
> For the users relying on an LTS JDK we can keep building Mandrel 23.1 from https://github.com/graalvm/graalvm-for-jdk21-community-backports
> 
> This is expected to leave those users without access to more recent GraalVM features and improvements that might not be accepted for a backport in GraalVM for JDK 21. In this case the users will need to wait until the Mandrel 25.1 release (September 2025) which is planned to be built on top of the LTS JDK 25. This is also aligned with the upstream OpenJDK release cadence.

Yes.

**Comment by zakkak** [comment]
I am closing this as not planned.
