### ISSUE TITLE
[23.0] Mandrel 23.0 fails to build with JDK 17.0.10-EA

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#607]
## Description
Mandrel 23.0 fails to build with JDK 17.0.10-EA with error:

```
Error: Substitution target for com.oracle.svm.core.jdk.Target_javax_crypto_JceSecurity_IdentityWrapper is invalid as inner class IdentityWrapper in javax.crypto.JceSecurity can not be found. Make sure that the inner class is present.
```

This is due to the upstream JDK 17 change in https://github.com/openjdk/jdk17u/commit/a06047acce82f60b5ca193a7b2aa329ed24b46f4

**Comment by jerboaa** [comment]
JDK bug: https://bugs.openjdk.org/browse/JDK-8316589

**Comment by jerboaa** [comment]
Fixed with https://github.com/graalvm/mandrel/pull/609
