### ISSUE TITLE
[CI] ~/.docker/config.json issues (file not found) - mandrel docker client header step

### ISSUE THREAD

**Issue by jerboaa** [graalvm/mandrel#642]
## Description

After #641 we still see issues in CI related to setting the user agent in docker config:

```
 jq: error: Could not open file /home/runner/.docker/config.json: No such file or directory
/home/runner/work/_temp/61a2380e-b2d9-4100-b3a7-1686a4b14df3.sh: line 1: /home/runner/.docker/config.json.new: No such file or directory
Error: Process completed with exit code 1.
```

See for example:
https://github.com/graalvm/mandrel/actions/runs/7248996212/job/19747102268?pr=640#step:10:25

Looks to me that those expected files `~/.docker/config.json` aren't there on some runners to begin with. We need to figure out what creates them and run those commands first.

**Comment by zakkak** [comment]
Upstream Quarkus (where we got this part of the pipeline from originally) [added a check to see if the file exists or not.](https://github.com/quarkusio/quarkus/pull/37798)
