### ISSUE TITLE
[23.0] Backport: Fix Cpuid1Ecx feature parsing for AMD CPUs

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#659]
## What would you like to backport?
https://github.com/oracle/graal/pull/8159

## Why?
Fixes a somewhat rare case of checking which features are marked as enabled in `LZCNT`. 

## Are the changes being backported merged in upstream Graal?

- [x] Yes
- [ ] No

**Comment by MatiasT** [comment]
Hey there 👋 
it has been almost 2 months since this was open, is there any reason for this fix not to be backported here?

**Comment by zakkak** [comment]
This [has been backported upstream](https://github.com/graalvm/graalvm-for-jdk17-community-backports/commit/979fdc8825c60a6bb31287734f8496ef2da5783f).
