### ISSUE TITLE
[23.1] Backport: Fix Cpuid1Ecx feature parsing for AMD CPUs

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#660]
## What would you like to backport?
https://github.com/oracle/graal/pull/8159

## Why?
Fixes a somewhat rare case of checking which features are marked as enabled in `LZCNT`. 

## Are the changes being backported merged in upstream Graal?

- [x] Yes
- [ ] No

**Comment by MatiasT** [comment]
Hey there 👋 
it has been almost 2 months since this was open, is there any reason for this fix not to be backported here?

**Comment by zakkak** [comment]
This [has been backported upstream](https://github.com/graalvm/graalvm-for-jdk21-community-backports/commit/5d15e9ea7671ac6476d4a07db5738a0cbba6eeef).

**Comment by parasjain27031994** [comment]
Hi @zakkak , is it possible for you to let us know, when will 23.1.3.0-Final will be available ? 
We are observing this issue in https://github.com/graalvm/mandrel/releases/tag/mandrel-23.1.2.0-Final as well.

> 1/8] Initializing...                                                                                   (12.0s @ 0.21GB)
>  Java version: 21.0.2+13-LTS, vendor version: Mandrel-23.1.2.0-Final
>  Graal compiler: optimization level: 2, target machine: x86-64-v3
>  C compiler: gcc (redhat, x86_64, 8.5.0)
>  Garbage collector: Serial GC (max heap size: 80% of RAM)

**Comment by zakkak** [comment]
Hi @parasjain27031994, 23.1.3.0-Final is planned for late April 2024

**Comment by parasjain27031994** [comment]
Hi @zakkak , just checking in, if we have a release date finalized for this 23.1.3.0-Final ?

**Comment by zakkak** [comment]
Hi @parasjain27031994, unfortunately not. Hopefully we will be able to release it in April, but it's not fixed yet.

**Comment by parasjain27031994** [comment]
Hi @zakkak , is it still targeted for April ? What's blocking the release if I may ask ?

**Comment by AnandRa007** [comment]
Hello @zakkak, is this [issue/8143](https://github.com/oracle/graal/issues/8143) /  [8159](https://github.com/oracle/graal/pull/8159) fixed in any of the versions that has been [released](https://docs.oracle.com/en/graalvm/release-calendar.html) recently ?

**Comment by zakkak** [comment]
Hi @AnandRa007 the issue should be fixed (by https://github.com/graalvm/mandrel/commit/45f599e3dc293749c0ab52c7c5336149878fe948) in Mandrel 23.1.3.1-Final, the releases you are linking to are Oracle GraalVM releases and as answered by @fniephaus in https://github.com/oracle/graal/issues/8143#issuecomment-2104089917 they should also include the fix for this issue.
