### ISSUE TITLE
 Mandrel graal/master (24.1-dev) fails to build with JDK 23+6

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#665]
## Description
$title

## Additional context

Build fails with

```
/home/runner/work/mandrel/mandrel/mandrel/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jfr/JfrManager.java:207: error: cannot find symbol
                        PrivateAccess.getInstance().getPlatformRecording(recording).setDumpOnExitDirectory(new SecuritySupport.SafePath(p));
                                                                                   ^
  symbol:   method setDumpOnExitDirectory(SafePath)
  location: class PlatformRecording
```

The method was replaced/renamed in https://bugs.openjdk.org/browse/JDK-8323425

**Comment by zakkak** [comment]
Upstream patch expected to fix the issue: https://github.com/oracle/graal/pull/8221

**Comment by jerboaa** [comment]
See for example this CI failure here:
https://github.com/graalvm/mandrel/actions/runs/7605339328/job/20709486048#step:8:393

**Comment by zakkak** [comment]
The upstream patch (https://github.com/oracle/graal/pull/8221) is now merged and the issue is resolved.

See https://github.com/graalvm/mandrel/actions/runs/7634228747
