### ISSUE TITLE
[24.0] Backport: Break class initialization cycle in XML classes.

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#674]
## What would you like to backport?
https://github.com/oracle/graal/pull/8256

## Why?
Fixes https://github.com/oracle/graal/issues/8075

## Are the changes being backported merged in upstream Graal?

- [x] Yes
- [ ] No

**Comment by jerboaa** [comment]
I'm going to backport this to the 24.0 tree (ahead of upstream), so that we get more CI runs (as JDK 23-based mandrel seems bust).

**Comment by jerboaa** [comment]
PR in #677. I'll merge once CI looks good.

Edit: The upstream change has arrived, so #677 is obsolete.

**Comment by jerboaa** [comment]
https://github.com/oracle/graal/commit/df761b6bb7178647ed29bacddf6e54ef183fded0 is the release branch commit. I'll rebase the mandrel branch and close it then.

**Comment by zakkak** [comment]
I rebased `mandrel/24.0` and https://github.com/graalvm/mandrel/commit/df761b6bb7178647ed29bacddf6e54ef183fded0 is now part of it.

**Comment by jerboaa** [comment]
Thanks!
