### ISSUE TITLE
[22.3] Mandrel 22.3 builds fail with JDK 17.0.11 EA

### ISSUE THREAD

**Issue by jerboaa** [graalvm/mandrel#689]
## Description
Same issues as #680 and #684. We need to backport both fixes to the 22.3 release tree.

CI is failing due to this.

See the CI failures here:
https://github.com/graalvm/mandrel/actions/runs/8119296504/job/22195386898#step:12:488
https://github.com/graalvm/mandrel/actions/runs/8119296504/job/22195386783#step:11:19333

**Comment by zakkak** [comment]
Fixed by #694 and #695
