### ISSUE TITLE
Mandrel `graal/master` fails to build with JDK 23+13 

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#692]
## Description
https://bugs.openjdk.org/browse/JDK-8309622 removed `sun.util.locale.LocaleObjectCache` which is used by `com.oracle.svm.hosted.jdk.localization.LocalizationFeature` resulting in build failures with:

```
/home/runner/work/mandrel/mandrel/mandrel/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/jdk/localization/LocalizationFeature.java:100: error: cannot find symbol
import sun.util.locale.LocaleObjectCache;
                      ^
  symbol:   class LocaleObjectCache
  location: package sun.util.locale
1 error
```

See https://github.com/graalvm/mandrel/actions/runs/8226350267/job/22492670878

The issue should get fixed with the next upstream `23+13-jvmci` sync (PR not available yet).

**Comment by zakkak** [comment]
Upstream PR for the 23+13-jvmci sync https://github.com/oracle/graal/pull/8545

Issue expected to be fixed by https://github.com/oracle/graal/pull/8545/commits/34a45ca70c094c01cc845afd4a9d18edbe37f493

**Comment by jerboaa** [comment]
Fixed with the merge upstream.
