### ISSUE TITLE
Mandrel 23.1 fails to build with 21.0.4-beta+1-ea

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#732]
## Description

Mandrel 23.1 fails to build with 21.0.4-beta+1-ea due to the backport (https://bugs.openjdk.org/browse/JDK-8326968) of https://bugs.openjdk.org/browse/JDK-8321270

**Comment by zakkak** [comment]
There is an upstream PR fixing this https://github.com/graalvm/graalvm-for-jdk21-community-backports/pull/1

**Comment by jerboaa** [comment]
Should be closed with https://github.com/graalvm/mandrel/pull/738

**Comment by zakkak** [comment]
#738 is now merged and the CI looks green https://github.com/graalvm/mandrel/actions/runs/9269776255
