### ISSUE TITLE
CI: Build graal/master with JDK 24, create release/24.1 branch for JDK 23 based builds

### ISSUE THREAD

**Issue by jerboaa** [graalvm/mandrel#749]
The oracle/graal tree has moved on to JDK 24 for building. Currently we still build graal master with JDK 23 which produces warnings and causes issues like https://github.com/graalvm/mandrel-packaging/issues/429 causing the build to fail.

We should:

1. Update CI to build master branch with JDK 24 EA. Related upstream issue for the release branch is [here](https://github.com/oracle/graal/issues/9127).
2. Create a `mandrel/24.1` release branch for JDK 23 EA based CI builds in preparation for the GraalVM for JDK 23 release in September, 2024.

**Comment by jerboaa** [comment]
I've created a `mandrel/24.1` branch, pointing to [communicated the branch point](https://github.com/oracle/graal/issues/9127#issuecomment-2186882044), for JDK 23 based builds.

**Comment by jerboaa** [comment]
https://github.com/graalvm/mandrel/pull/750 is switching the nightly builds to use the JDK 23 release branch.

**Comment by jerboaa** [comment]
The GraalVM for JDK 23 release branch has now been created as is being mirrored upstream: https://github.com/oracle/graal/tree/release/graal-vm/24.1

**Comment by jerboaa** [comment]
FYI: I've just synced the mandrel 24.1 release branch with the version from upstream.

**Comment by zakkak** [comment]
The CI part was also fixed in https://github.com/graalvm/mandrel/pull/754
