### ISSUE TITLE
[24.1] Backport: [GR-54733] Warn about deprecated config files in META-INF directories

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#760]
## What would you like to backport?
https://github.com/oracle/graal/pull/9155

## Why?
Improves warning message and fixes https://github.com/oracle/graal/issues/9057

## Are the changes being backported merged in upstream Graal?

- [X] Yes
- [ ] No

**Comment by jerboaa** [comment]
@zakkak JDK 23 (24.1) is nearing release day. If we want this in Mandrel for JDK 23, we need to prioritize it.

**Comment by zakkak** [comment]
Backported upstream in https://github.com/graalvm/mandrel/commit/79c1171b5fa58d8b67d50a5eed0ccfd71a7c0355 as part of https://github.com/oracle/graal/pull/9450
