### ISSUE TITLE
[24.1] Backport: Updated JFR substitutions from [GR-54877]

### ISSUE THREAD

**Issue by roberttoyonaga** [graalvm/mandrel#763]
## What would you like to backport?
Some JFR substitutions need to be updated. This labsjdk 24+3 updates patch fixes them in GraalVM https://github.com/oracle/graal/pull/9181

The whole patch should not be backported. Just the JFR parts (since the OpenJDK JFR patch was backported from 24 to 23). 
## Why?
Native image builds will fail if JFR is included.  See: https://github.com/graalvm/mandrel/actions/runs/9762948079/job/26949412202?pr=762  and  https://github.com/graalvm/mandrel/pull/762#issuecomment-2206219679

## Are the changes being backported merged in upstream Graal?

- [x] Yes
- [ ] No

**Comment by zakkak** [comment]
@roberttoyonaga I think we can close this now that https://github.com/graalvm/mandrel/pull/764 is merged, right?

**Comment by jerboaa** [comment]
I think so. Fixed with #764.
