### ISSUE TITLE
Mandrel 24.2.0 throws WARNING: Unknown module: org.graalvm.truffle specified to --enable-native-access

### ISSUE THREAD

**Issue by zakkak** [graalvm/mandrel#805]
## Description
Since https://github.com/oracle/graal/pull/9892 mandrel issues the following warning:

```
WARNING: Unknown module: org.graalvm.truffle specified to --enable-native-access
```

## How To Reproduce
```
path/to/mandrel-java24-24.2.0-deve05805b1084/bin/native-image HelloWorld
```

### Configuration:
 - OS: Fedora 40
 - Architecture: AMD64
 - Mandrel version: 24.2.0-deve05805b1084
 - JDK version: 24+20-ea

## Expected behavior
No warning should be shown.

## Additional context
Since we don't ship truffle we need to remove it from the `--enable-native-access` in mandrel builds.

**Comment by jerboaa** [comment]
@zakkak Does the same occur with community builds with `--no-jlinking`? If so I suggest raising it upstream.

**Comment by zakkak** [comment]
> @zakkak Does the same occur with community builds with `--no-jlinking`? If so I suggest raising it upstream.

I think that's not related to jlinking, but related to whether the build includes the truffle api package or not. I have an upstream fix ready, which I am currently testing :)

**Comment by jerboaa** [comment]
OK

**Comment by jerboaa** [comment]
Re-opening as the warning is still there.

**Comment by jerboaa** [comment]
Upstream PR which should fix this is now https://github.com/oracle/graal/pull/9964

**Comment by jerboaa** [comment]
Closing this since https://github.com/oracle/graal/pull/9964 has now been integrated.
