### ISSUE TITLE
Create major.minor floating tag in quay

### ISSUE THREAD

**Issue by galderz** [graalvm/mandrel#95]
We should have a `20.1` tag on quay that links to the latest Mandrel release. This moving tag would allow users to get the latest 20.1 version and would help avoid version specific hardcoding. See https://github.com/quarkusio/quarkus/pull/11061 for details.

**Comment by galderz** [comment]
We might additionally want to have a `major.minor-javaX` tag, in case we want to specifically refer to something that only applies to a certain java version. So, `20.1-java11` as well as `20.1`.

**Comment by zakkak** [comment]
Imagine the following scenario:
User compiles code on machine A and happens to get 20.1.0.0 for tag `20.1`.
Same user compiles same code on machine B but this time they get 20.1.0.1 for tag `20.1`.
User now observes different performance/behaviour between machine A and B while using the exact same configuration.
I find this confusing for both the user and us trying to debug what's wrong.

Furthermore, having a `20.1` tag means we need to make sure that whenever we release a `20.1.x.x` image we need to make sure it works with all quarkus versions (or any other framework we decide to support in the future) mentioning tag `20.1` in their docs. In theory 20.1.x.x should not introduce breaking changes but to enforce this we should perform extensive testing, which complicates and slows things down.

Regarding

**Comment by galderz** [comment]
I think the risks of introducing breaking changes in micro.x releases is very small.

The downside of this [full reference](https://github.com/quarkusio/quarkus/pull/11061/files#diff-cbe7e4692ea77ee1f632145becb13ed9R37) is that it will be updated in no time. You'll have to update it when final comes out, when the next CP comes out...etc. It's not scalable. Using a floating tag helps avoid the need to update it. We'd only have to worry updating the doc when we switch to `20.2`.

Everyone knows you should not use snapshots or rolling tag when building things seriously, for say production. You'd never pick a `latest` tag in docker. You'd go figure out the exact release you need and use that. However, a rolling tag works just fine if you're doing dev, or just trying to get something going quickly.

**Comment by zakkak** [comment]
> I think the risks of introducing breaking changes in micro.x releases is very small.

That would be true if Mandrel was following [semantic versioning](https://semver.org/).
However the `major.minor.micro` prefix in Mandrel just denotes the GraalVM CE release that the Mandrel release is based on.
The chances of backporting a breaking change I would like to think that are indeed very small, but still not guaranteed (especially without extensive testing).

> The downside of this [full reference](https://github.com/quarkusio/quarkus/pull/11061/files#diff-cbe7e4692ea77ee1f632145becb13ed9R37) is that it will be ~updated~ out of date in no time. You'll have to update it when final comes out, when the next CP comes out...etc. It's not scalable. Using a floating tag helps avoid the need to update it. We'd only have to worry updating the doc when we switch to `20.2`.

Correct. @gsmet what are your thoughts about this? In Quarkus you have been doing this kind of updates for GraalVM already.
The difference here is that Mandrel _might_ be releasing more often than GraalVM.

> Everyone knows you should not use snapshots or rolling tag when building things seriously, for say production. You'd never pick a `latest` tag in docker. You'd go figure out the exact release you need and use that. However, a rolling tag works just fine if you're doing dev, or just trying to get something going quickly.

I think we should make this extra bolt in the documentation though, because `20.1` is not `latest` so someone may assume it maps to a single release. On the other hand images of linux distros do the same e.g. fedora:32, ubuntu:18.04 etc. So maybe it's not that surprising to have a "moving" `20.1`. 

(just sharing my thoughts, no strong opinion)

**Comment by jerboaa** [comment]
I'd be +1 to having a moving `20.1`. It's pretty common practice. After all, the version numbers for Graal VM are based on the year, AFAIK. So users of the image going with `20.1` tag wouldn't get `20.2` or `21.1` Graal VM by surprise. They would get images with base OS updates, micro release respins etc. There is a small? chance of such minor bumps causing regressions of some form but it would be a risk worth taking. The risk of people hard-coding to a *specific* image with known vulnerabilities in it seems greater. They wouldn't be able to rebuild using `20.1` tag and getting updated packages.

**Comment by zakkak** [comment]
https://github.com/quarkusio/quarkus-images/pull/92 has been merged. Starting from Sunday we should have a 20.1-java11 tag :)

**Comment by galderz** [comment]
The tag is [there](https://quay.io/repository/quarkus/ubi-quarkus-mandrel?tab=tags) now. I'll update the docs.

**Comment by galderz** [comment]
Sent a [Quarkus PR](https://github.com/quarkusio/quarkus/pull/11551) to use the floating tag now that it's available.
